language: android
jdk: oraclejdk8
before_install:
- nvm install 6
- node --version
install:
- cd examples && cd RNOneSignal && npm install
android:
  components:
  - build-tools-23.0.1
  - build-tools-27.0.3
  - android-23
  - android-27
  - extra-android-m2repository
  - extra-google-google_play_services
  - extra-google-m2repository
  - addon-google_apis-google-16
script:
- cd android && ./gradlew assembleRelease
